apiVersion: apps/v1
kind: Deployment
metadata: 
  name: feedback
  labels:
    app: feedback
    type: front-end 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feedback
      type: front-end 
  template:
    metadata:
      labels:
        app: feedback
        type: front-end 
    spec: 
      containers:
      - name: feedback
        image: ganesharavind124/flaskapp:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/my_flask_app_db"
